/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import controllers.PaymentController;
import java.awt.Color;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Payment;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import other.ComboSearch;

/**
 *
 * @author Dell
 */
public class DatePayments extends javax.swing.JPanel {

    private final DefaultTableModel model;
    private final DefaultTableModel model2;
    private  int a;

    /**
     * Creates new form DatePayments
     */
    public DatePayments() {
        initComponents();
        a=0;
        setCombo();
        a=1;
        
        model = (DefaultTableModel) table.getModel();
        model2=(DefaultTableModel)tab2.getModel();
        setTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        rText = new javax.swing.JLabel();
        refreshLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        rsTotal = new javax.swing.JLabel();
        $Total = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(571, 528));
        setName("Sort By Date"); // NOI18N
        setPreferredSize(new java.awt.Dimension(571, 528));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        datePicker.setDate(new Date());
        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Month");

        table.setForeground(new java.awt.Color(107, 5, 4));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "RID", "Date", "Amount US$", "Amount Rs", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(table);

        rText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rText.setForeground(new java.awt.Color(255, 0, 0));
        rText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rText.setText("Refresh");

        refreshLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images/images/ref2.png"))); // NOI18N
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Date");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Year");

        yearCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboItemStateChanged(evt);
            }
        });

        monthCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboItemStateChanged(evt);
            }
        });

        tab2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tab2.setForeground(new java.awt.Color(107, 5, 4));
        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "RID", "Date", "AmountUS", "AmountRs", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab2);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        rsTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rsTotal.setForeground(new java.awt.Color(204, 0, 0));
        rsTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rsTotal.setText("0.0");

        $Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        $Total.setForeground(new java.awt.Color(204, 0, 0));
        $Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        $Total.setText("0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(rText)
                                .addGap(5, 5, 5)
                                .addComponent(refreshLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent($Total, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printButton)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent($Total, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        setTable();
    }//GEN-LAST:event_datePickerActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setTable();
        //rText.setForeground(Color.red);
    }//GEN-LAST:event_formComponentShown

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        setTable();
        rText.setForeground(Color.green);
        refreshLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images/images/011_yes-128.png")));
        setTable2();

    }//GEN-LAST:event_refreshLabelMouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        //rText.setForeground(Color.red);
    }//GEN-LAST:event_formComponentHidden

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        rText.setForeground(Color.red);
        refreshLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images/images/ref2.png")));
        
    }//GEN-LAST:event_formMouseExited

    private void yearComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboItemStateChanged
        if (a==0) {
            return ;
        }
        setTable2();
    }//GEN-LAST:event_yearComboItemStateChanged

    private void monthComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboItemStateChanged
        if (a==0) {
            return ;
        }
        setTable2();
    }//GEN-LAST:event_monthComboItemStateChanged

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        String year=yearCombo.getSelectedItem().toString();
        String month="December";
        String monthNum=monthCombo.getSelectedItem().toString();
        if (monthNum.equals("1")) {
            month="January";
        }
        if (monthNum.equals("2")) {
            month="February";
        }
        if (monthNum.equals("3")) {
            month="March";
        }
        if (monthNum.equals("4")) {
            month="April";
        }
        if (monthNum.equals("5")) {
            month="May";
        }
        if (monthNum.equals("6")) {
            month="June";
        }
        if (monthNum.equals("7")) {
            month="July";
        }
        if (monthNum.equals("8")) {
            month="August";
        }
        if (monthNum.equals("9")) {
            month="September";
        }
        if (monthNum.equals("10")) {
            month="October";
        }
        if (monthNum.equals("11")) {
            month="November";
        }
        InputStream iS = getClass().getResourceAsStream("/Reports/DatePayments.jrxml");
        HashMap<String,Object> h=new HashMap<>();
        h.put("Year", year);
        h.put("Month",month);
        h.put("Doller",$Total.getText());
        h.put("Rs",rsTotal.getText());
        try {
            JasperReport compileReport = JasperCompileManager.compileReport(iS);
            JasperPrint fillReport = JasperFillManager.fillReport(compileReport, h,new JRTableModelDataSource(model2));
            JasperViewer.viewReport(fillReport,false);
        } catch (JRException ex) {
            Logger.getLogger(DatePayments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $Total;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel rText;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JLabel rsTotal;
    private javax.swing.JTable tab2;
    private org.jdesktop.swingx.JXTable table;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables

    private void setTable() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String date = format.format(datePicker.getDate());
        model.setRowCount(0);
        try {
            ArrayList<Payment> p1 = PaymentController.getPaymentsofDate(date);
            if (p1.isEmpty()) {
                return;
            }
            for (Payment p : p1) {
                model.addRow(new Object[]{p.getPid(), p.getRid(), p.getDate(), p.getAmountUS$(), p.getAmountRs(), p.getRate()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(AllPayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCombo() {
        monthCombo.addItem("1");
        monthCombo.addItem("2");
        monthCombo.addItem("3");
        monthCombo.addItem("4");
        monthCombo.addItem("5");
        monthCombo.addItem("6");
        monthCombo.addItem("7");
        monthCombo.addItem("8");
        monthCombo.addItem("9");
        monthCombo.addItem("10");
        monthCombo.addItem("11");
        monthCombo.addItem("12");
        new ComboSearch().setSearchableCombo(monthCombo, true, "No result found...");
        SimpleDateFormat s1=new SimpleDateFormat("yyyy");
        int curYear = Integer.parseInt(s1.format(new Date()));
        int m=2016;
        for (int i = m; i <= curYear; i++) {
            yearCombo.addItem(i+"");
        }
        new ComboSearch().setSearchableCombo(yearCombo, true, "No result found...");
        
        
    }

    private void setTable2() {
        model2.setRowCount(0);
        String year=yearCombo.getSelectedItem().toString();
        String month=monthCombo.getSelectedItem().toString();
        try {
            ArrayList<Payment> p1=PaymentController.getPaymentsOfMonth(year,month);
            if (p1.isEmpty()) {
                $Total.setText("0.0");
                rsTotal.setText("0.0");
                return ;
            }
            for (Payment p : p1) {
                model2.addRow(new Object[]{p.getPid(),p.getRid(),p.getDate(),p.getAmountUS$(),p.getAmountRs(),p.getRate()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatePayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatePayments.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTotal();
        
        
    }

    private void setTotal() {
        double $=0;
        double rs=0;
        for (int i = 0; i < tab2.getRowCount(); i++) {
            $+=Double.parseDouble(model2.getValueAt(i, 3).toString());
            rs+=Double.parseDouble(model2.getValueAt(i, 4).toString());
        }
        $Total.setText($+"");
        rsTotal.setText(rs+"");
        
        
        
    }
}
