/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.DocumentController;
import controllers.ExperienceController;
import controllers.NokController;
import controllers.SeaGuardController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import model.Documents;
import model.Experiences;
import model.Nok;
import other.ComboSearch;
import other.Validation;

/**
 *
 * @author Dell
 */
public class OtherDetails extends javax.swing.JPanel {

    /**
     * Creates new form OtherDetails
     */
    public OtherDetails() {
        initComponents();
        setSids();
        setService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        relationText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tele1Text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tele2Text = new javax.swing.JTextField();
        nokSaveButton = new javax.swing.JLabel();
        nokUpdateButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        policeReportCheckBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        medicalReportCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cdcNoText = new javax.swing.JTextField();
        yfCardNoText = new javax.swing.JTextField();
        bankPassbookText = new javax.swing.JTextField();
        passportNotext = new javax.swing.JTextField();
        noObjectionCheckBox = new javax.swing.JCheckBox();
        nokNicText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        documentSaveButton = new javax.swing.JLabel();
        documentUpdateButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        serviceComboBox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        rankText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        branchText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        durationText = new javax.swing.JTextField();
        exSaveButton = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1175, 675));
        setName("Other Details\n"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1175, 675));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Next Of Kin's Details");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Documents");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Experiences");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SID");

        sidCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sidComboItemStateChanged(evt);
            }
        });
        sidCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidComboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Relation");

        relationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telephone   -(Land)");

        tele1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tele1TextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                     (Mobile)");

        tele2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tele2TextActionPerformed(evt);
            }
        });

        nokSaveButton.setBackground(new java.awt.Color(255, 153, 153));
        nokSaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nokSaveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nokSaveButton.setText("Save");
        nokSaveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        nokSaveButton.setOpaque(true);
        nokSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nokSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nokSaveButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nokSaveButtonMouseClicked(evt);
            }
        });

        nokUpdateButton.setBackground(new java.awt.Color(255, 153, 153));
        nokUpdateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nokUpdateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nokUpdateButton.setText("Update");
        nokUpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        nokUpdateButton.setOpaque(true);
        nokUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nokUpdateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nokUpdateButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nokUpdateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(sidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(relationText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tele1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tele2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nokUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nokSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(relationText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tele1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tele2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nokSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nokUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Police Report");

        policeReportCheckBox.setText("Given");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medical Report");

        medicalReportCheckBox.setText("Given");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NIC No.");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NIC No. of NOK");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No Objection Letter");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Passport No.");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bank Passbook No.");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Yellow Fever Card No.");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CDC No.");

        cdcNoText.setMinimumSize(new java.awt.Dimension(6, 15));
        cdcNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdcNoTextActionPerformed(evt);
            }
        });

        yfCardNoText.setMinimumSize(new java.awt.Dimension(6, 15));
        yfCardNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yfCardNoTextActionPerformed(evt);
            }
        });

        bankPassbookText.setMinimumSize(new java.awt.Dimension(6, 15));
        bankPassbookText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankPassbookTextActionPerformed(evt);
            }
        });

        passportNotext.setMinimumSize(new java.awt.Dimension(6, 15));
        passportNotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportNotextActionPerformed(evt);
            }
        });

        noObjectionCheckBox.setText("Given");

        nokNicText.setMinimumSize(new java.awt.Dimension(6, 15));
        nokNicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokNicTextActionPerformed(evt);
            }
        });
        nokNicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nokNicTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nokNicTextKeyReleased(evt);
            }
        });

        nicText.setMinimumSize(new java.awt.Dimension(6, 15));
        nicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextActionPerformed(evt);
            }
        });
        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicTextKeyTyped(evt);
            }
        });

        documentSaveButton.setBackground(new java.awt.Color(255, 153, 153));
        documentSaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        documentSaveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        documentSaveButton.setText("Save");
        documentSaveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        documentSaveButton.setOpaque(true);
        documentSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documentSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documentSaveButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                documentSaveButtonMouseClicked(evt);
            }
        });

        documentUpdateButton.setBackground(new java.awt.Color(255, 153, 153));
        documentUpdateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        documentUpdateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        documentUpdateButton.setText("Update");
        documentUpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        documentUpdateButton.setOpaque(true);
        documentUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documentUpdateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documentUpdateButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                documentUpdateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(policeReportCheckBox))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nokNicText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passportNotext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankPassbookText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yfCardNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicalReportCheckBox)
                            .addComponent(noObjectionCheckBox))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(documentUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(documentSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policeReportCheckBox))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(medicalReportCheckBox)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noObjectionCheckBox))
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nokNicText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(passportNotext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bankPassbookText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(yfCardNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cdcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Service");

        serviceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceComboBoxActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Rank");

        rankText.setMinimumSize(new java.awt.Dimension(6, 15));
        rankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankTextActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Branch");

        branchText.setMinimumSize(new java.awt.Dimension(6, 15));
        branchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchTextActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Duration");

        durationText.setMinimumSize(new java.awt.Dimension(6, 15));
        durationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextActionPerformed(evt);
            }
        });
        durationText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durationTextKeyTyped(evt);
            }
        });

        exSaveButton.setBackground(new java.awt.Color(255, 153, 153));
        exSaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exSaveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exSaveButton.setText("Save");
        exSaveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        exSaveButton.setOpaque(true);
        exSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exSaveButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exSaveButtonMouseClicked(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        cancelButton.setOpaque(true);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(exSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(serviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(rankText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(branchText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(durationText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(serviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rankText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(branchText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(485, 485, 485))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void cdcNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdcNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdcNoTextActionPerformed

    private void tele2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tele2TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tele2TextActionPerformed

    private void tele1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tele1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tele1TextActionPerformed

    private void relationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationTextActionPerformed

    private void nicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextActionPerformed

    private void nokNicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokNicTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nokNicTextActionPerformed

    private void passportNotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportNotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportNotextActionPerformed

    private void bankPassbookTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankPassbookTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankPassbookTextActionPerformed

    private void yfCardNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yfCardNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yfCardNoTextActionPerformed

    private void sidComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidComboActionPerformed

    private void serviceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceComboBoxActionPerformed

    private void branchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchTextActionPerformed

    private void rankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankTextActionPerformed

    private void durationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setSids();
    }//GEN-LAST:event_formComponentShown

    private void sidComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sidComboItemStateChanged
        searchNok();
        searchDoc();
        searchEx();
    }//GEN-LAST:event_sidComboItemStateChanged

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited

    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered

    }//GEN-LAST:event_jPanel1MouseEntered

    private void nokSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokSaveButtonMouseEntered
        enter(nokSaveButton);
    }//GEN-LAST:event_nokSaveButtonMouseEntered

    private void nokSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokSaveButtonMouseExited
        exit(nokSaveButton);
    }//GEN-LAST:event_nokSaveButtonMouseExited

    private void nokSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokSaveButtonMouseClicked
        saveNok();
    }//GEN-LAST:event_nokSaveButtonMouseClicked

    private void nokUpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokUpdateButtonMouseEntered
        enter(nokUpdateButton);
    }//GEN-LAST:event_nokUpdateButtonMouseEntered

    private void nokUpdateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokUpdateButtonMouseExited
        exit(nokUpdateButton);
    }//GEN-LAST:event_nokUpdateButtonMouseExited

    private void nokUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nokUpdateButtonMouseClicked
        updateNok();
    }//GEN-LAST:event_nokUpdateButtonMouseClicked

    private void documentSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentSaveButtonMouseEntered
        enter(documentSaveButton);
    }//GEN-LAST:event_documentSaveButtonMouseEntered

    private void documentSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentSaveButtonMouseExited
        exit(documentSaveButton);
    }//GEN-LAST:event_documentSaveButtonMouseExited

    private void documentSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentSaveButtonMouseClicked
        saveDocument();
    }//GEN-LAST:event_documentSaveButtonMouseClicked

    private void documentUpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentUpdateButtonMouseEntered
        enter(documentUpdateButton);
    }//GEN-LAST:event_documentUpdateButtonMouseEntered

    private void documentUpdateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentUpdateButtonMouseExited
        exit(documentUpdateButton);
    }//GEN-LAST:event_documentUpdateButtonMouseExited

    private void documentUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentUpdateButtonMouseClicked
        updateDoc();
    }//GEN-LAST:event_documentUpdateButtonMouseClicked

    private void exSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exSaveButtonMouseEntered
        enter(exSaveButton);
    }//GEN-LAST:event_exSaveButtonMouseEntered

    private void exSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exSaveButtonMouseExited
        exit(exSaveButton);
    }//GEN-LAST:event_exSaveButtonMouseExited

    private void exSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exSaveButtonMouseClicked
        addEx();
    }//GEN-LAST:event_exSaveButtonMouseClicked

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
        enter(cancelButton);
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited
        exit(cancelButton);
    }//GEN-LAST:event_cancelButtonMouseExited

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void nicTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyTyped

    }//GEN-LAST:event_nicTextKeyTyped

    private void nicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyReleased

    }//GEN-LAST:event_nicTextKeyReleased

    private void nokNicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nokNicTextKeyReleased

    }//GEN-LAST:event_nokNicTextKeyReleased

    private void nicTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyPressed
        Validation.validationNIC(nicText);
    }//GEN-LAST:event_nicTextKeyPressed

    private void nokNicTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nokNicTextKeyPressed
        Validation.validationNIC(nokNicText);
    }//GEN-LAST:event_nokNicTextKeyPressed

    private void durationTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTextKeyTyped
        char ch = evt.getKeyChar();
        if (!(Character.isDigit(ch) || Character.toString(ch).equals("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_durationTextKeyTyped
    public void enter(Component c) {
        c.setBackground(Color.red);
        c.setForeground(Color.white);
    }

    public void exit(Component c) {
        c.setBackground(new Color(255, 153, 153));
        c.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField bankPassbookText;
    private javax.swing.JTextField branchText;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JTextField cdcNoText;
    private javax.swing.JLabel documentSaveButton;
    private javax.swing.JLabel documentUpdateButton;
    private javax.swing.JTextField durationText;
    private javax.swing.JLabel exSaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox medicalReportCheckBox;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nicText;
    private javax.swing.JCheckBox noObjectionCheckBox;
    private javax.swing.JTextField nokNicText;
    private javax.swing.JLabel nokSaveButton;
    private javax.swing.JLabel nokUpdateButton;
    private javax.swing.JTextField passportNotext;
    private javax.swing.JCheckBox policeReportCheckBox;
    private javax.swing.JTextField rankText;
    private javax.swing.JTextField relationText;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JComboBox<String> sidCombo;
    private javax.swing.JTextField tele1Text;
    private javax.swing.JTextField tele2Text;
    private javax.swing.JTextField yfCardNoText;
    // End of variables declaration//GEN-END:variables

    private void setSids() {
        sidCombo.removeAllItems();
        try {
            ArrayList<String> sids = SeaGuardController.getAllSids();

            for (String sid : sids) {
                sidCombo.addItem(sid);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageSeaGuardForm1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSeaGuardForm1.class.getName()).log(Level.SEVERE, null, ex);
        }
        new ComboSearch().setSearchableCombo(sidCombo, true, "No result found...");
    }

    private void saveNok() {
        String sid = sidCombo.getSelectedItem().toString();
        String name = nameText.getText();
        String relaton = relationText.getText();
        String address = addressText.getText();
        String tele = tele1Text.getText();
        String mobile = tele2Text.getText();

        try {
            if (NokController.addNok(new Nok(sid, name, relaton, address, tele, mobile))) {
                JOptionPane.showMessageDialog(OtherDetails.this, "Added Successfully...");
            } else {
                JOptionPane.showMessageDialog(OtherDetails.this, "Adding Failed...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
        setSids();
    }

    private void clearTextFields() {
        nameText.setText("");
        addressText.setText("");
        relationText.setText("");
        tele1Text.setText("");
        tele2Text.setText("");

    }

    private void searchNok() {
        clearTextFields();
        if (sidCombo.getItemCount() == 0) {
            return;
        }
        Nok nok;
        try {
            nok = NokController.searchNok(sidCombo.getSelectedItem().toString());
            if (nok == null) {
                return;
            }
            nameText.setText(nok.getName());
            relationText.setText(nok.getRelation());
            addressText.setText(nok.getAddress());
            tele1Text.setText(nok.getTele());
            tele2Text.setText(nok.getMobile());

        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void updateNok() {
        String sid = sidCombo.getSelectedItem().toString();
        String name = nameText.getText();
        String relaton = relationText.getText();
        String address = addressText.getText();
        String tele = tele1Text.getText();
        String mobile = tele2Text.getText();

        try {
            if (NokController.UpdateNok(new Nok(sid, name, relaton, address, tele, mobile))) {
                JOptionPane.showMessageDialog(OtherDetails.this, "Updated Successfully...");
            } else {
                JOptionPane.showMessageDialog(OtherDetails.this, "Updete Failed...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
        setSids();
    }

    private void saveDocument() {
        String a = sidCombo.getSelectedItem().toString();
        boolean b = policeReportCheckBox.isSelected();
        boolean c = medicalReportCheckBox.isSelected();
        String d = nicText.getText();
        String e = nokNicText.getText();
        boolean f = noObjectionCheckBox.isSelected();
        String g = passportNotext.getText();
        String h = bankPassbookText.getText();
        String i = yfCardNoText.getText();
        String j = cdcNoText.getText();
        boolean statues = checkDoc();
        try {
            if (DocumentController.addDocument(new Documents(a, b, c, d, e, f, g, h, i, j, statues))) {
                JOptionPane.showMessageDialog(OtherDetails.this, "Added Successfully...");
            } else {
                JOptionPane.showMessageDialog(OtherDetails.this, "Adding Failed...");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(OtherDetails.this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(OtherDetails.this, ex.getMessage());
        }

    }

    private void searchDoc() {
        try {
            if (sidCombo.getItemCount() == 0) {
                return;
            }
            Documents doc = DocumentController.searchDoc(sidCombo.getSelectedItem().toString());
            if (doc == null) {
                clearDoc();
                return;
            }
            clearDoc();
            policeReportCheckBox.setSelected(doc.isPoliceReport());
            medicalReportCheckBox.setSelected(doc.isMedicalReport());
            nicText.setText(doc.getNicNo());
            nokNicText.setText(doc.getNicNoNOK());
            noObjectionCheckBox.setSelected(doc.isNoObjectionLetter());
            passportNotext.setText(doc.getPassportNo());
            bankPassbookText.setText(doc.getBankPassbookNo());
            yfCardNoText.setText(doc.getYellowFeverCardNo());
            cdcNoText.setText(doc.getCdcNo());
        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clearDoc() {
        policeReportCheckBox.setSelected(false);
        medicalReportCheckBox.setSelected(false);
        nicText.setText(null);
        nokNicText.setText(null);
        noObjectionCheckBox.setSelected(false);
        passportNotext.setText(null);
        bankPassbookText.setText(null);
        yfCardNoText.setText(null);
        cdcNoText.setText(null);
    }

    private void updateDoc() {
        String a = sidCombo.getSelectedItem().toString();
        boolean b = policeReportCheckBox.isSelected();
        boolean c = medicalReportCheckBox.isSelected();
        String d = nicText.getText();
        String e = nokNicText.getText();
        boolean f = noObjectionCheckBox.isSelected();
        String g = passportNotext.getText();
        String h = bankPassbookText.getText();
        String i = yfCardNoText.getText();
        String j = cdcNoText.getText();
        boolean statues = checkDoc();
        try {
            if (DocumentController.updateDocument(new Documents(a, b, c, d, e, f, g, h, i, j, statues))) {
                JOptionPane.showMessageDialog(OtherDetails.this, "Updated Successfully...");
            } else {
                JOptionPane.showMessageDialog(OtherDetails.this, "Update Failed...");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(OtherDetails.this, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(OtherDetails.this, ex.getMessage());
        }
        setSids();
    }

    private void searchEx() {
        clearEx();
        try {
            if (sidCombo.getItemCount() == 0) {
                return;
            }
            Experiences xp = ExperienceController.getExperience(sidCombo.getSelectedItem().toString());
            if (xp == null) {
                return;
            }
            rankText.setText(xp.getRank());
            durationText.setText(xp.getDuration());
            branchText.setText(xp.getBranch());
        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addEx() {
        String sid = sidCombo.getSelectedItem().toString();
        String service = serviceComboBox.getSelectedItem().toString();
        String rank = rankText.getText();
        String branch = branchText.getText();
        String duration = durationText.getText();
        try {
            if (ExperienceController.addExperience(new Experiences(sid, service, rank, duration, branch))) {
                JOptionPane.showMessageDialog(OtherDetails.this, "Added Successfully...");
            } else {
                JOptionPane.showMessageDialog(OtherDetails.this, "Adding Failed...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OtherDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
        setSids();

    }

    private void setService() {
        serviceComboBox.removeAll();
        serviceComboBox.addItem("Army");
        serviceComboBox.addItem("Navy");
        serviceComboBox.addItem("Air Force");

    }

    private boolean checkDoc() {
        boolean b1 = policeReportCheckBox.isSelected();
        boolean b2 = medicalReportCheckBox.isSelected();
        boolean b3 = noObjectionCheckBox.isSelected();
        boolean b4 = !nicText.getText().isEmpty();
        boolean b5 = !nokNicText.getText().isEmpty();
        boolean b6 = !passportNotext.getText().isEmpty();
        boolean b7 = !bankPassbookText.getText().isEmpty();
        boolean b8 = !yfCardNoText.getText().isEmpty();
        boolean b9 = !cdcNoText.getText().isEmpty();
        if (b1 & b2 & b3 & b4 & b5 & b6 & b7 & b8 & b9) {
            return true;
        }
        return false;

    }

    private void clearEx() {
        serviceComboBox.setSelectedItem("Army");
        rankText.setText("");
        durationText.setText("");
        branchText.setText("");
    }

}
