/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.ReservationController;
import controllers.SeaGuardController;
import controllers.ShipController;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Reservation;
import model.Ship;
import other.ComboSearch;

/**
 *
 * @author Dell
 */
public class ReservationView extends javax.swing.JPanel {

    /**
     * Creates new form Reservation
     */
    public ReservationView() {
        initComponents();
        setDate();
        setRid();
        setSids();
        setShIds();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sidComboBox = new org.jdesktop.swingx.JXComboBox();
        jLabel14 = new javax.swing.JLabel();
        seaGuardNameText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        shIdComboBox = new org.jdesktop.swingx.JXComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shipIdCombo = new org.jdesktop.swingx.JXComboBox();
        jLabel12 = new javax.swing.JLabel();
        shipOwnerNameText = new javax.swing.JTextField();
        shipNameText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ridText = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        dateText = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signInDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        signOutDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        signInPort = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        signOutPort = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        salaryText = new javax.swing.JTextField();
        saveButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1175, 675));
        setName("Reservation"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1175, 675));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reservation");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true), "Select Sea Guard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SID");

        sidComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        sidComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sidComboBoxItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name");

        seaGuardNameText.setEditable(false);
        seaGuardNameText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seaGuardNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seaGuardNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0)));
        seaGuardNameText.setPreferredSize(new java.awt.Dimension(59, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(sidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seaGuardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(seaGuardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true), "Select Sea Guard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Owner Id");

        shIdComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        shIdComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shIdComboBoxItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Owner Name");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ship Id");

        shipIdCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        shipIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shipIdComboItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ship Name");

        shipOwnerNameText.setEditable(false);
        shipOwnerNameText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        shipOwnerNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shipOwnerNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0)));
        shipOwnerNameText.setPreferredSize(new java.awt.Dimension(59, 25));

        shipNameText.setEditable(false);
        shipNameText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        shipNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shipNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0)));
        shipNameText.setPreferredSize(new java.awt.Dimension(59, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(shIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(22, 22, 22)
                .addComponent(shipOwnerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shipIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shipNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(shipIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(shipNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(shipOwnerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RID");

        ridText.setEditable(false);
        ridText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        ridText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ridText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ridText.setPreferredSize(new java.awt.Dimension(8, 20));
        ridText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");

        dateText.setEditable(false);
        dateText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        dateText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateText.setPreferredSize(new java.awt.Dimension(8, 20));
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ridText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ridText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sign in Date");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 12, -1, 35));

        signInDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        signInDate.setDate(new Date());
        signInDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInDateMouseClicked(evt);
            }
        });
        signInDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                signInDateInputMethodTextChanged(evt);
            }
        });
        signInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInDateActionPerformed(evt);
            }
        });
        jPanel5.add(signInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sign out Date");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 12, -1, 35));

        signOutDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        signOutDate.setDate(new Date());
        signOutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutDateActionPerformed(evt);
            }
        });
        jPanel5.add(signOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sign in Port");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 53, -1, 35));

        signInPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signInPort.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel5.add(signInPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 58, 106, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sign out Port");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 35));

        signOutPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signOutPort.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel5.add(signOutPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 58, 117, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agreed Salary");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 99, -1, 35));

        salaryText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salaryText.setPreferredSize(new java.awt.Dimension(59, 25));
        salaryText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTextKeyTyped(evt);
            }
        });
        jPanel5.add(salaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 99, 106, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        saveButton.setBackground(new java.awt.Color(255, 153, 153));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveButton.setText("Save");
        saveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        saveButton.setOpaque(true);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        enter(saveButton);
    }//GEN-LAST:event_saveButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        exit(saveButton);
        
    }//GEN-LAST:event_saveButtonMouseExited

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
       save();
    }//GEN-LAST:event_saveButtonMouseClicked

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void ridTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridTextActionPerformed

    private void sidComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sidComboBoxItemStateChanged
        searchName();

    }//GEN-LAST:event_sidComboBoxItemStateChanged

    private void shIdComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shIdComboBoxItemStateChanged
        searchShipOwner();
        setShips();
    }//GEN-LAST:event_shIdComboBoxItemStateChanged

    private void shipIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shipIdComboItemStateChanged
        setShipName();
    }//GEN-LAST:event_shipIdComboItemStateChanged

    private void salaryTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTextKeyReleased
        
    }//GEN-LAST:event_salaryTextKeyReleased

    private void signInDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_signInDateInputMethodTextChanged
        
    }//GEN-LAST:event_signInDateInputMethodTextChanged

    private void signInDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInDateMouseClicked
        
    }//GEN-LAST:event_signInDateMouseClicked

    private void signInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInDateActionPerformed
        findDuration();
    }//GEN-LAST:event_signInDateActionPerformed

    private void signOutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutDateActionPerformed
        findDuration();
    }//GEN-LAST:event_signOutDateActionPerformed

    private void salaryTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTextKeyTyped
        char ch=evt.getKeyChar();
        if (!Character.isDigit(ch)) {
            evt.consume();
        }
    }//GEN-LAST:event_salaryTextKeyTyped
    public void enter(Component c){
        c.setBackground(Color.red);
        c.setForeground(Color.white);
    }
    public void exit(Component c){
        c.setBackground(new Color(255, 153, 153));
        c.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFormattedTextField ridText;
    private javax.swing.JTextField salaryText;
    private javax.swing.JLabel saveButton;
    private javax.swing.JTextField seaGuardNameText;
    private org.jdesktop.swingx.JXComboBox shIdComboBox;
    private org.jdesktop.swingx.JXComboBox shipIdCombo;
    private javax.swing.JTextField shipNameText;
    private javax.swing.JTextField shipOwnerNameText;
    private org.jdesktop.swingx.JXComboBox sidComboBox;
    private org.jdesktop.swingx.JXDatePicker signInDate;
    private javax.swing.JTextField signInPort;
    private org.jdesktop.swingx.JXDatePicker signOutDate;
    private javax.swing.JTextField signOutPort;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        SimpleDateFormat s1=new SimpleDateFormat("yyyy-MM-dd");
        dateText.setText(s1.format(new Date()));
    }

    private void setRid() {
        
        try {
            ridText.setText(ReservationController.getNextRid());
            
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setSids() {
        try {
            sidComboBox.removeAllItems();
            ArrayList<String> sList=SeaGuardController.getSelectedSids();
            if (sList==null) {
                return ;
            }
            for (String sid: sList) {
                sidComboBox.addItem(sid);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
        new ComboSearch().setSearchableCombo(sidComboBox, true, "No result found...");
        
    }

    
    

    private void searchName() {
        try {
            String sid=sidComboBox.getSelectedItem().toString();
            String name=SeaGuardController.searchName(sid);
            seaGuardNameText.setText(name);
                    
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchShipOwner() {
        try {
            if (shIdComboBox.getSelectedItem()==null) {
                return ;
            }
            String shId=shIdComboBox.getSelectedItem().toString();
            String name=ShipController.searchShipOwner(shId);
            if (name==null) {
                return ;
            }
            shipOwnerNameText.setText(name);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setShIds() {
        try {
            shIdComboBox.removeAll();
            ArrayList<String> s1=ShipController.getShIds();
            if (s1==null) {
                return ;
            }
            for (String s : s1) {
                shIdComboBox.addItem(s);
            }
            new ComboSearch().setSearchableCombo(shIdComboBox, true, "No result found...");
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void setShips() {
        shipIdCombo.removeAllItems();
        try {
             if (shIdComboBox.getSelectedItem()==null) {
                return ;
            }
           
            String shId=shIdComboBox.getSelectedItem().toString();
            ArrayList<Ship> s1=ShipController.getShips(shId);
            for (Ship s : s1) {
                shipIdCombo.addItem(s.getShipId());
            }
            new ComboSearch().setSearchableCombo(shipIdCombo, true, "No result found...");
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
    }

    private void setShipName() {
        try {
            if (shipIdCombo.getSelectedItem()==null) {
                shipNameText.setText("");
                return ;
            }
            String shipId=shipIdCombo.getSelectedItem().toString();
            String name = ShipController.searchShip(shipId);
            shipNameText.setText(name);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void save() {
        String rid=ridText.getText();
        String sid=sidComboBox.getSelectedItem().toString();
        String shipId=shipIdCombo.getSelectedItem().toString();
        String date=dateText.getText();
        Date sIDate=signInDate.getDate();
        Date sODate=signOutDate.getDate();
        String sIPort=signInPort.getText();
        String sOPort=signOutPort.getText();
        double salary=Double.parseDouble(salaryText.getText());
        SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        String sID=format.format(sIDate);
        String sOD=format.format(sODate);
        
        
        Reservation r=new Reservation(rid,sid,shipId,date,sID,sOD,sIPort,sOPort,salary);
        try {
            if (ReservationController.addReservation(r)) {
                JOptionPane.showMessageDialog(ReservationView.this, "Saved Successfully...");
            } else {
                JOptionPane.showMessageDialog(ReservationView.this, "Failed...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
          
    }

    private void reset() {
        try {
            ridText.setText(ReservationController.getNextRid());
        } catch (SQLException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
        sidComboBox.setSelectedIndex(0);
        
        signInPort.setText("");
        signOutPort.setText("");
        salaryText.setText("");
    }

    private void findDuration() {
        
    }
}
